export const FLIGHT_DATE_DATA = `
DELIMITER $$

DROP PROCEDURE IF EXISTS ADD_FLIGHT_DATE_LOOP $$
CREATE PROCEDURE ADD_FLIGHT_DATE_LOOP ()
BEGIN
    DECLARE V_COUNTER INT UNSIGNED DEFAULT 0;
    DECLARE V_MAX INT UNSIGNED DEFAULT 56;
    DECLARE DEP_DATE DATE DEFAULT CURDATE();
    DECLARE FID CHAR(5);

    WHILE V_COUNTER < V_MAX DO
        BLOCK_CURSOR: BEGIN
            DECLARE DONE INT DEFAULT 0;
            DECLARE CUR0 CURSOR FOR
                SELECT FLIGHT_ID
                FROM FLIGHT_DAY
                WHERE DAY_OF_WEEK = DAYOFWEEK(DEP_DATE);
            DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;
            OPEN CUR0;
            ITR: LOOP
                FETCH CUR0 INTO FID;
                IF DONE = 1 THEN
                    LEAVE ITR;
                END IF;
                INSERT INTO FLIGHT_DATE VALUES (FID, DEP_DATE, '00:00:00', 'AVAILABLE');
            END LOOP ITR;
            CLOSE CUR0;
            SET V_COUNTER = V_COUNTER + 1;
            SET DEP_DATE = DATE_ADD(DEP_DATE, INTERVAL 1 DAY);
        END BLOCK_CURSOR;
    END WHILE;
END $$

CALL ADD_FLIGHT_DATE_LOOP() $$

DELIMITER ;
DELIMITER $$
`