export const SCHEMA = `
DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS FLIGHT_DATE;
DROP TABLE IF EXISTS FLIGHT_DAY;
DROP TABLE IF EXISTS FLIGHT_PATH;
DROP TABLE IF EXISTS AIRPORT;
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL_ID VARCHAR(30) UNIQUE NOT NULL,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    GENDER ENUM ('M','F','O'),
    DOB DATE,
    ROLE ENUM ('N','R','W') NOT NULL,
    PROFESSION ENUM ('STUDENT', 'ARMYPERSONNEL', 'SENIORCITIZEN', 'OTHER') NOT NULL,
    COUNTRY_CODE VARCHAR(4) NOT NULL,
    PHONE_NO VARCHAR(11) NOT NULL,
    ADDRESS VARCHAR(60)
);

CREATE TABLE AIRPORT (
    AIRPORT_ID CHAR(3) PRIMARY KEY,
    AIRPORT_NAME VARCHAR(80) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL,
    OFFSET TIME NOT NULL,
    CONSTRAINT UCC UNIQUE (CITY, COUNTRY)
);

CREATE TABLE FLIGHT_PATH (
    FLIGHT_ID CHAR(5) PRIMARY KEY,
    SOURCE_ID CHAR(3) NOT NULL,
    DESTINATION_ID CHAR(3) NOT NULL,
    DEPARTURE_TIME TIME NOT NULL,
    DURATION TIME NOT NULL,
    NUM_ROWS INT NOT NULL,
    NUM_COLS INT NOT NULL,
    BASE_FARE INT NOT NULL,
    LEASE_EXPIRY DATE NOT NULL,
    FOREIGN KEY (SOURCE_ID) REFERENCES AIRPORT(AIRPORT_ID) ON DELETE CASCADE,
    FOREIGN KEY (DESTINATION_ID) REFERENCES AIRPORT(AIRPORT_ID) ON DELETE CASCADE
);

CREATE TABLE FLIGHT_DAY (
    FLIGHT_ID CHAR(5) NOT NULL,
    DAY_OF_WEEK ENUM ('1','2','3','4','5','6','7') NOT NULL,
    PRIMARY KEY (FLIGHT_ID, DAY_OF_WEEK),
    FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT_PATH(FLIGHT_ID) ON DELETE CASCADE
);

CREATE TABLE FLIGHT_DATE (
    FLIGHT_DATE_ID INT PRIMARY KEY AUTO_INCREMENT,
    FLIGHT_ID CHAR(5) NOT NULL,
    DEPARTURE_DATE DATE NOT NULL,
    DELAYED_BY TIME NOT NULL,
    FLIGHT_STATUS ENUM ('AVAILABLE', 'CANCELLED'),
    FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT_PATH(FLIGHT_ID),
    CONSTRAINT UNFD UNIQUE (FLIGHT_ID, DEPARTURE_DATE)
);
ALTER TABLE FLIGHT_DATE AUTO_INCREMENT 700001;

CREATE TABLE TICKET (
    TICKET_ID INT PRIMARY KEY AUTO_INCREMENT,
    FLIGHT_DATE_ID INT NOT NULL,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    PASSENGER_NAME VARCHAR(30) NOT NULL,
    PASSENGER_AGE INT NOT NULL,
    TIME_OF_BOOKING DATETIME NOT NULL,
    FARE INT NOT NULL,
    ROW_NUM INT NOT NULL,
    COL_NUM INT NOT NULL,
    STATUS ENUM ('BOOKED', 'CANCELLED') NOT NULL,
    TIME_OF_CANCELLATION DATETIME,
    REIMBURSED_AMOUNT INT
);
ALTER TABLE TICKET AUTO_INCREMENT 10000001;

DELIMITER $$
`;
